version: "3"

x-basic-setting: &basic-setting
  init: true
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "2G"
      max-file: "2"
      compress: "true"

networks:
  cloudflare-ddns:
    name: cloudflare-ddns
    driver: bridge

services:
  cloudflare-ddns:
    <<: *basic-setting
    image: docker.io/newjett0617/cloudflare-ddns:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudflare-ddns
    networks:
      - cloudflare-ddns
    environment:
      - DOMAIN=${DOMAIN}
      - ZONE_ID=${ZONE_ID}
      - API_TOKEN=${API_TOKEN}
      - INTERVAL_TIME=${INTERVAL_TIME}
